batch_size = 52
do_profile = false
num_epochs = 100
regressor = "vit"
task = "diled"

[voxelizer]
max_unique_species = 5
n_grid = 24
distance_power = 2.0
eff_scale = 0.7
num_cells = 4

[data]
data_batch_size = 52
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 8
test_split = 3
valid_split = 3
do_augment = false
augment_seed = 12345
so3 = true
o3 = true
t3 = true

[cli]
verbosity = "info"
show_progress = true

[device]
device = "gpu"
max_gpus = 1
gpu_ids = []

[log]
log_dir = "logs"
logs_per_epoch = 8

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 0.004
end_lr_frac = 0.04
weight_decay = 0.03
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 1.0

[diled]
patch_latent_dim = 8
patch_conv_sizes = [5]
patch_conv_strides = [3]
patch_conv_features = [1]
species_embed_dim = 56
w = 1

[diled.backbone]
condition_mlp_dims = [128]
time_dim = 64
label_dim = 64
condition_dropout = 0.2

[diled.diffusion]
schedule_a = 1.7
schedule_b = 1.9
timesteps = 100
class_dropout = 0.5

[diled.category]
category_loss_type = "e_form"
num_cats = 8

[diled.backbone.time_mlp]
inner_dims = []
dropout = 0.1
equivariant = false

[diled.backbone.encoder]
equivariant = true
num_layers = 2
num_heads = 4
enc_dropout_rate = 0.1
enc_attention_dropout_rate = 0.0

[diled.backbone.time_mlp.activation]
name = "relu"

[diled.backbone.time_mlp.final_activation]
name = "Identity"

[diled.backbone.encoder.mlp]
inner_dims = []
dropout = 0.1
equivariant = false

[diled.backbone.encoder.mlp.activation]
name = "relu"

[diled.backbone.encoder.mlp.final_activation]
name = "Identity"
