batch_size = 64
do_profile = false
num_epochs = 50
regressor = "vit"
task = "diled"

[voxelizer]
max_unique_species = 4
n_grid = 24
distance_power = 2.4
eff_scale = 0.7
num_cells = 4

[data]
dataset_name = "jarvis_dft3d_cleaned"
raw_data_folder = "data"
data_folder = "precomputed"
shuffle_seed = 1618
train_split = 4
test_split = 1
valid_split = 20
do_augment = false

[data_transform]
density_transform_name = "sqrt"
density_scale = 2
density_shift = 0

[cli]
verbosity = "info"
show_progress = true

[train]
lr_schedule_kind = "cosine"
start_lr_frac = 0.1
base_lr = 0.001
end_lr_frac = 0.01
weight_decay = 0
beta_1 = 0.9
beta_2 = 0.999
nestorov = true
max_grad_norm = 3.0

[diled]
patch_latent_dim = 128
patch_conv_sizes = [5]
patch_conv_strides = [3]
patch_conv_features = [64]
species_embed_dim = 32
w = 0

[diled.backbone]
condition_mlp_dims = [64]
time_dim = 64
label_dim = 64
condition_dropout = 0.2

[diled.diffusion]
schedule_a = 1.7
schedule_b = 1.9
timesteps = 100
class_dropout = 0.25

[diled.category]
category_loss_type = "cubic_space_group"

[diled.backbone.time_mlp]
inner_dims = []
dropout = 0.1
equivariant = false

[diled.backbone.encoder]
equivariant = true
num_layers = 3
num_heads = 16
enc_dropout_rate = 0.1
enc_attention_dropout_rate = 0.1

[diled.head]
inner_dims = [256]
dropout = 0.1
equivariant = false

[diled.backbone.time_mlp.activation]
name = "gelu"

[diled.backbone.time_mlp.final_activation]
name = "Identity"

[diled.backbone.encoder.mlp]
inner_dims = []
dropout = 0.1
equivariant = false

[diled.backbone.encoder.mlp.activation]
name = "gelu"

[diled.backbone.encoder.mlp.final_activation]
name = "Identity"
